name: metar
description: An aviation weather METAR/SPECI parser library.
version: 0.0.1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  fraction: ^4.1.0

dev_dependencies:
  archive: ^3.3.0
  lints: ^1.0.0
  test: ^1.20.2
