name: metar
description: An aviation weather METAR/SPECI parser library.
version: 0.0.1

environment:
  sdk: '>=2.16.0-80.1.beta <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.2
